kind: Deployment
apiVersion: "extensions/v1beta1"
metadata:
  name: "rlt-test"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: "rlt-test"
    spec:
      containers:
      - name: "rlt-test"
        image: "gcr.io/elasticsearch-236916/rlt-test:latest"
        ports:
        - containerPort: 80